version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
      APP_USER: InputGenerator
      APP_USER_PASSWORD: 123456
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "echo", "SELECT 1 FROM DUAL;", "|", "sqlplus", "InputGenerator/123456@localhost:1521/XEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10

  app:
    container_name: node-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - oracle
    environment:
      PORT: 5000
      ORACLE_USER: InputGenerator
      ORACLE_PASSWORD: 123456
      ORACLE_CONNECT_STRING: oracle:1521/XEPDB1
      JWT_TOKEN: sdmnakjdbakhwbrjhabkdsnbajasdawfgrsg
    volumes:
      - .:/app

volumes:
  oracle-data:
